name: gitartwork from a contribution graph
on:
    push:
    schedule:
        - cron: "* */24 * * *"
jobs:
    build:
        name: Make gitartwork SVG
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: Penguinlay/gitartwork@v1
              with:
                  # Use this username's contribution graph
                  user_name: Penguinlay
                  # Text on contribution graph
                  text: ğŸ¼SheinğŸ§
            - uses: jasineri/simple-push-action@v1
